<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-12-12T01:43:19 IST" name="Suite" finished-at="2022-12-12T01:43:56 IST" duration-ms="36953">
    <groups>
    </groups>
    <test started-at="2022-12-12T01:43:19 IST" name="Test" finished-at="2022-12-12T01:43:56 IST" duration-ms="36953">
      <class name="testCases.SignUpTestCases">
        <test-method is-config="true" signature="browserlaunch()[pri:0, instance:testCases.SignUpTestCases@485966cc]" started-at="2022-12-12T01:43:29 IST" name="browserlaunch" finished-at="2022-12-12T01:43:40 IST" duration-ms="10968" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserlaunch -->
        <test-method signature="veryfySignUp()[pri:0, instance:testCases.SignUpTestCases@485966cc]" started-at="2022-12-12T01:43:40 IST" name="veryfySignUp" finished-at="2022-12-12T01:43:56 IST" duration-ms="16019" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- veryfySignUp -->
      </class> <!-- testCases.SignUpTestCases -->
      <class name="testCases.logInTestsCase">
        <test-method is-config="true" signature="browserlaunch()[pri:0, instance:testCases.logInTestsCase@505fc5a4]" started-at="2022-12-12T01:43:19 IST" name="browserlaunch" finished-at="2022-12-12T01:43:27 IST" duration-ms="7935" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserlaunch -->
        <test-method signature="method1()[pri:0, instance:testCases.logInTestsCase@505fc5a4]" started-at="2022-12-12T01:43:27 IST" name="method1" finished-at="2022-12-12T01:43:29 IST" duration-ms="1966" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [lease check your username and password. If you still can't log in, contact your Salesforce administrator.] but found [Please check your username and password. If you still can't log in, contact your Salesforce administrator.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [lease check your username and password. If you still can't log in, contact your Salesforce administrator.] but found [Please check your username and password. If you still can't log in, contact your Salesforce administrator.]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at resources.Commonmethods.assertionmethod(Commonmethods.java:31)
at testCases.logInTestsCase.method1(logInTestsCase.java:36)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method1 -->
      </class> <!-- testCases.logInTestsCase -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
